### ISSUE TITLE
Handling <ESC> + <release ESC> + <another key>

### ISSUE THREAD

**Issue by tdy** [ililim/dual-key-remap#4]
This is a common sequence in my workflow: <kbd>ESC</kbd> + <kbd>release ESC</kbd> + <kbd>another key</kbd>. It comes up a lot in vim, bash, etc.

The problem is when I do these keystrokes quickly, a lot of times I haven't 100% released <kbd>ESC</kbd> before hitting the next key. This causes dual-key-remap to register it as a <kbd>CTRL</kbd> modifier instead.

Apart from the physical workaround of typing slower to make sure I fully release <kbd>ESC</kbd> every time, is there a programmatic way to handle this? Maybe a configurable millisecond delay when checking `remappedKeyState` or something?

**Comment by tdy** [comment]
I wonder if [readline's *keyseq-timeout*](https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html) concept would be applicable here.

> Specifies the duration Readline will wait for a character when reading an ambiguous key sequence (one that can form a complete key sequence using the input read so far, or can take additional input to complete a longer key sequence). If no input is received within the timeout, Readline will use the shorter but complete key sequence. Readline uses this value to determine whether or not input is available on the current input source (rl_instream by default). The value is specified in milliseconds, so a value of 1000 means that Readline will wait one second for additional input. If this variable is set to a value less than or equal to zero, or to a non-numeric value, Readline will wait until another key is pressed to decide which key sequence to complete. The default value is 500.

**Comment by tdy** [comment]
Sorry, I meant to cancel my followup reply but hit "close and comment" accidentally.

**Comment by ililim** [comment]
Interesting. I did some tests and this behaviour does seem consistent with the rest of the modifier keys. Presing <kbd>Ctrl</kbd>+<kbd>Z</kbd> in quick succession so that there is a tiny overlap results in the undo command being issued.

My concern with adding a configurable delay is that there might not be a number that feels good accross all situations. For example (assuming the default remappings): Imagine a user presses <kbd>CAPSLOCK</kbd> then <kbd>C</kbd> very quickly, resulting in the two key presses overlapping briefly. Did the user intend to send <kbd>CTRL</kbd>+<kbd>C</kbd> or <kbd>CTRL</kbd> and <kbd>C</kbd> seperately? 

In some cases it will be the former; in others it will be the latter. I don't see a way that dual-key-remap could distinguish between the two reliably, so I would rather the utility would stay consistent with how the rest of the modifier keys behave.

That said, I'm open to other suggestions.

**Comment by ililim** [comment]
A similar problem was referenced in #11. I think the best way of handling this is to only trigger the `with_other` modifier when another key is pressed _down_ while holding the modifier (as opposed to when any key is pressed both _up_ or _down_). This is implemented in the [latest release (v0.4)](https://github.com/ililim/dual-key-remap/releases).
