### ISSUE TITLE
Security error when installing

### ISSUE THREAD

**Issue by keyurshah** [ililim/dual-key-remap#6]
Unfortunately I get security errors and virus alerts when installing on Windows 10. It prevents me from opening the executable.

Thanks.

**Comment by ililim** [comment]
Thanks for reporting this. Can you attach a screenshot or the error code for the security error / virus alert? I know one of the errors can be disabled by clicking 'more info' and 'run anyway'.

I did a test through Virus Total and indeed 9/70 engines complain about the executable. I suspect it's because the utility is not well known yet and it modifies keyboard input in the background – that may seem suspicious to them. I'll reach out to the various engines to report the false positive.

If anyone doubts the executable, it's quite easy to compile your own from the source code. Install Visual Studio and then run the commands described [at the bottom of the README](https://github.com/ililim/dual-key-remap#Developing).

**Comment by keyurshah** [comment]
Thanks for your assistance.

The issue was caused by Windows Defender. Here is a screenshot of what it's reporting. (I tried to click "more info" and 'run anyway' but it still would not continue). I will probably try with defender disabled, but once I turn it on, it will probably reject it.

![image](https://user-images.githubusercontent.com/744385/50499701-90f89a00-0a00-11e9-9992-063e4c2ca6f2.png)

**Comment by ililim** [comment]
Does adding a [security exclusion](https://support.microsoft.com/en-ca/help/4028485/windows-10-add-an-exclusion-to-windows-security) work as a temporary work-around?

I've reported the false positive to Microsoft; it will probably take a while for them to review the app and update their Windows Defender virus definitions.

**Comment by ililim** [comment]
Microsoft has removed the false positive from Defender:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by ililim** [comment]
I've reached out to some other bigger vendors also, but with future releases I will probably only keep tabs on Windows Defender. If anyone else's antivirus flags the binary feel free to open a new issue. (Although these days arguably it's [better to just use Windows Defender](https://news.ycombinator.com/item?id=13489100))

**Comment by keyurshah** [comment]
this seems to have fixed it and works fine now.

thanks!
