### ISSUE TITLE
<CAPSLOCK> and <ESC> not registered in certain programs

### ISSUE THREAD

**Issue by Melkster** [ililim/dual-key-remap#7]
I have binded `CAPSLOCK` to `ESC` when tapped and `CTRL` when combined with other key like so:

```
remap_key=VK_ESCAPE
when_alone=VK_ESCAPE
with_other=VK_CONTROL
```

This works in most applications. However, in some games (e.g. League of Legends), **both** `CAPSLOCK` and `ESC` are dead, i.e. they do nothing when pressed.

Turning off `dual-key-remap.exe` enables these keys again.

**Comment by ililim** [comment]
Does this happen with any programs that are not League of Legends? If so, could you list them? I'll try to debug the common theme and see if there what the issue is.

After some reading it seems that League of Legends is notorious for not being compatible with software that modifies keyboard inputs (AutoHotkey doesn't work well either). I assume this has to do with their anti-bot/cheat measures, which inadvertently ends up breaking legitimate tools also.

A potential improvement for this tool would be registering a menubar item that allows the user to temporarily disable the utility, so the they can use the normal keyset for certain applications. Or even better an application blacklist.

**Comment by Melkster** [comment]
I haven't had the time to try out that many games, but here are a couple of games that don't register `ESC` with `dual-key-remap.exe` running:

- Hitman Absolution
- Subnautica
- Apex Legends
- Dishonored in the main meny and in game pause menu for some reason. `ESC` does work in game though (it brings up the pause menu, but doesn't close it when I hit `ESC` again, which it should)

**Comment by shawjak3** [comment]
Another program that this happens to is Visual Studio Code. I use vim and was really wanting to use this but once I run this my capslock and escape are both dead.

**Comment by ililim** [comment]
@shawjak3 I use dual-key-remap with VS Code also and it works for me. Do you run Visual Studio Code as administrator? If you do then dual-key-remap must also run as administrator (see #1).

**Comment by shawjak3** [comment]
@ililim I have tried both ways in both programs and it just makes capslock and escape do nothing system wide.

**Comment by Konfekt** [comment]
dual-key-remap works fine over here, but in such instances, it might be interesting to use the various autohotkey scripts such as

https://gist.github.com/sedm0784/4443120

and

https://github.com/fenwar/ahk-caps-ctrl-esc

as a fallback and report if the work fine.

**Comment by shawjak3** [comment]
@Konfekt I have tried those as well and I get the same behavior results; escape and capslock just don't work at all.

**Comment by ililim** [comment]
Good call on testing AHK @Konfekt.

@shawjak3 What version of OS are you running and do you use any other applications that modify keyboard input in any way? Autohotkey and dual-key-remap use the same Windows API to modify keyboard input, so the underlying cause is probably the same for both apps.

**Comment by shawjak3** [comment]
@ililim I'm running a fresh install of Windows 10 Home. I have no other applications that modify keyboard input. Those were the only 2 I tried and they behaved the same way. Makes sense to me if they use the same API underneath because I get exactly the same results. 

I'm trying to get used to `jj` for esacpe in vim in the meantime...really missing my capslock for escape haha. But I realize you guys do this as a help and on your own time so thanks for your time and help.

**Comment by Konfekt** [comment]
I am currently out of ideas other than recommending https://github.com/kana/vim-arpeggio as an alternative to `jj` inside Vim in the meanwhile.

**Comment by Konfekt** [comment]
Perhaps try a different keyboard layout, driver or, to test, switch the physical keyboard.

**Comment by shawjak3** [comment]
@Konfekt I tried a Corsair keyboard and the built in keyboard on my laptop and I get the same results. Thanks for all your suggestions guys, I'll keep checking back periodically to see if someone finds a fix or workaround.

**Comment by shawjak3** [comment]
Hey guys I wanted to report back and say that I had a keybinding I put in my vscode that mapped escape and capslock to escape in vim on linux that I carried over. Turns out that was interfering with this program. I removed those and it now works perfectly.

**Comment by ililim** [comment]
Move game specific discussion into it's own issue: https://github.com/ililim/dual-key-remap/issues/25
